2023-05-03 14:11:51,116::WARNING::This is a warning!!!
2023-05-03 14:11:51,116::ERROR::This is an error!
2023-05-03 14:11:51,116::CRITICAL::this is a critical state!
2023-05-03 14:11:51,116::ERROR::error is found
Traceback (most recent call last):
  File "C:\Users\Data Science\Desktop\Handbook_Python\logging_practice.py", line 45, in <module>
    1 / 0
ZeroDivisionError: division by zero
